### ISSUE TITLE
Python developer survey image has incorrect years in title

### ISSUE THREAD

**Issue by andy-sweet** [chanzuckerberg/czi-oss-training#74]
The title says 2020 and 2021, whereas the legend says 2022 and 2021.

![Screenshot 2023-08-29 at 11 23 45 AM](https://github.com/chanzuckerberg/czi-oss-training/assets/2608297/ea585546-41fe-4415-afff-33445fb24167)

The [surrounding text mentions 2022](https://github.com/chanzuckerberg/czi-oss-training/blob/95d9e385d329b13e4aa15fbe657afb7953a4f8cb/01-intro-to-os/03-understand-oss-governance.md?plain=1#L132) and the [alt-text mentions 2022/2021](https://github.com/chanzuckerberg/czi-oss-training/blob/95d9e385d329b13e4aa15fbe657afb7953a4f8cb/01-intro-to-os/03-understand-oss-governance.md?plain=1#L135), so I assume the title is incorrect.

This also appears to be incorrect in the [developer survey itself](https://lp.jetbrains.com/python-developers-survey-2022/#PurposesUsingPython), so I'd suggest upstreaming the fix (if possible) and/or cropping the title from the image in this repository.

**Comment by pavithraes** [comment]
Thanks for reporting, and great catch!

I don't think Jetbrains/PSF have open sources this presentation page, so all we can do is share this via email.

Cropping is a good idea, which we can implement immediately. Alternatively, we can switch to using this answer from the general developer survey results: https://www.jetbrains.com/lp/devecosystem-2022/python/#what-do-you-use-python-for-

**Comment by trallard** [comment]
Thanks for flagging this @andy-sweet 🙏🏽  I have passed the correction on the PSF survey side to the folks in the PSF.

@pavithraes could you tackle the removing the title bit?
